FROM golang:1.25.13-alpine AS build

WORKDIR /src
ARG DISPATCHER_BUILD_VERSION=dev
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -trimpath -ldflags="-s -w -X main.version=${DISPATCHER_BUILD_VERSION}" -o /out/cdt-dispatcher ./cmd/dispatcher

FROM alpine:3.22
RUN apk add --no-cache ca-certificates tzdata \
    && addgroup -S cdt-dispatcher \
    && adduser -S -D -H -G cdt-dispatcher cdt-dispatcher
COPY --from=build /out/cdt-dispatcher /usr/local/bin/cdt-dispatcher
USER cdt-dispatcher
EXPOSE 8443/tcp 8443/udp 9091/tcp
ENTRYPOINT ["/usr/local/bin/cdt-dispatcher"]
