<template>
  <div class="space-y-5 fade-in">
    <header class="flex flex-wrap items-end justify-between gap-4">
      <div><div class="eyebrow">DNS CONTROL PLANE</div><h1 class="page-title">DNS 入口管理</h1><p class="page-subtitle">通过 Provider 抽象层托管多台 CDT Relay 的入口记录，支持阿里云 DNS 与 Cloudflare。</p><p class="field-hint">保存 Provider 时会先验证凭证和 Zone 访问权限，验证失败不会入库。</p></div>
      <div class="flex flex-wrap gap-2"><button class="btn-ghost border border-slate-200" :disabled="syncing" @click="syncAll">{{ syncing ? '同步中...' : '同步全部记录' }}</button><button class="btn-primary" @click="openProvider()">添加 DNS Provider</button></div>
    </header>
    <div v-if="message.text" class="notice" :class="`notice-${message.type}`">{{ message.text }}</div>

    <section class="grid grid-cols-1 gap-4 xl:grid-cols-2">
      <article v-for="provider in store.dnsProviders" :key="provider.id" class="card p-5">
        <div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="flex items-center gap-2"><span class="provider-mark">{{ provider.type === 'cloudflare' ? 'CF' : 'ALI' }}</span><h2 class="truncate font-bold text-slate-800">{{ provider.name }}</h2></div><p class="mt-2 truncate font-mono text-[11px] text-slate-400">{{ provider.zone }}</p></div><span class="state-tag" :class="provider.enabled ? 'state-online' : ''">{{ provider.enabled ? '已启用' : '已停用' }}</span></div>
        <div class="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div class="info-box"><span>类型</span><strong>{{ provider.type === 'cloudflare' ? 'Cloudflare' : '阿里云 DNS' }}</strong></div><div class="info-box"><span>凭证</span><strong>{{ credentialLabel(provider) }}</strong></div><div class="info-box"><span>托管记录</span><strong>{{ recordsFor(provider.id).length }}</strong></div><div class="info-box"><span>最近测试</span><strong>{{ formatTime(provider.last_test_at) }}</strong></div></div>
        <div v-if="provider.last_error" class="mt-3 rounded-lg bg-red-50 px-3 py-2 text-xs leading-5 text-red-700">{{ provider.last_error }}</div>
        <div class="mt-4 flex flex-wrap justify-end gap-1 border-t border-slate-100 pt-3"><button class="btn-ghost px-2 py-1 text-xs" :disabled="busyId === provider.id" @click="testProvider(provider)">{{ busyId === provider.id ? '测试中...' : '测试连接' }}</button><button class="btn-ghost px-2 py-1 text-xs" :disabled="busyId === provider.id" @click="syncProvider(provider)">同步记录</button><button class="btn-ghost px-2 py-1 text-xs" @click="openProvider(provider)">编辑</button><button class="btn-danger px-2 py-1 text-xs" @click="removeProvider(provider)">删除</button></div>
      </article>
      <div v-if="!store.dnsProviders.length" class="card empty-panel xl:col-span-2">还没有配置 DNS Provider。先添加 Provider，再声明需要托管的 A 记录。</div>
    </section>

    <section class="card overflow-hidden">
      <div class="flex flex-wrap items-end justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 class="font-bold text-slate-800">托管记录</h2><p class="mt-1 text-xs text-slate-400">系统只会同步这里声明的记录，不会清理 DNS 区域中的其他记录。</p><p class="mt-1 text-xs text-slate-400">Agent 来源支持一次选择多台 Relay，并为每个 Agent 公网 IP 维护一条同名记录。</p></div><button class="btn-primary" :disabled="!store.dnsProviders.length" @click="openRecord()">添加记录</button></div>
      <div v-if="store.dnsRecords.length" class="divide-y divide-slate-100"><div v-for="record in store.dnsRecords" :key="record.id" class="record-row"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><strong class="font-mono text-xs text-slate-700">{{ record.name }}</strong><span class="record-type">{{ record.type }}</span><span class="state-tag" :class="record.status === 'synced' ? 'state-online' : record.status === 'error' ? 'state-error' : ''">{{ statusLabel(record.status) }}</span></div><p class="mt-1 truncate font-mono text-[11px] text-slate-400">{{ record.value }} · TTL {{ record.ttl }} · {{ providerName(record.provider_id) }}<span v-if="record.relay_node_id"> · {{ relayNodeName(record.relay_node_id) }}</span></p><p v-if="record.last_error" class="mt-1 text-[11px] text-red-600">{{ record.last_error }}</p></div><div class="flex shrink-0 gap-1"><button class="btn-ghost px-2 py-1 text-xs" @click="openRecord(record)">编辑</button><button class="btn-danger px-2 py-1 text-xs" @click="removeRecord(record)">删除</button></div></div></div><div v-else class="empty-panel">暂无托管记录</div>
    </section>

    <Modal v-if="providerForm.open" @close="providerForm.open=false"><form class="space-y-5" @submit.prevent="saveProvider"><div><div class="eyebrow">DNS PROVIDER</div><h2 class="mt-1 text-lg font-bold text-slate-900">{{ providerForm.id ? '编辑 DNS Provider' : '添加 DNS Provider' }}</h2></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label class="field-label">名称</label><input v-model="providerForm.name" class="input" placeholder="例如：主域名 DNS" /></div><div><label class="field-label">Provider</label><select v-model="providerForm.type" class="input"><option value="aliyun">阿里云 DNS</option><option value="cloudflare">Cloudflare</option></select></div><div class="sm:col-span-2"><label class="field-label">DNS Zone</label><input v-model="providerForm.zone" class="input" placeholder="7b.tn" /><p class="field-hint">填写托管区域根域名，不要填写 relay 子域名。</p></div><template v-if="providerForm.type === 'aliyun'"><div><label class="field-label">AccessKey ID</label><input v-model="providerForm.access_key_id" class="input" autocomplete="off" /></div><div><label class="field-label">AccessKey Secret <span v-if="providerForm.id" class="font-normal text-slate-400">留空保持不变</span></label><input v-model="providerForm.access_key_secret" type="password" class="input" autocomplete="new-password" /></div></template><template v-else><div class="sm:col-span-2"><label class="field-label">API Token <span v-if="providerForm.id" class="font-normal text-slate-400">留空保持不变</span></label><input v-model="providerForm.api_token" type="password" class="input" autocomplete="new-password" /><p class="field-hint">建议使用仅 DNS 编辑权限的 API Token。</p></div></template><div class="sm:col-span-2"><label class="flex items-center gap-2 text-sm text-slate-600"><input v-model="providerForm.enabled" type="checkbox" />启用自动同步</label></div></div><div v-if="formError" class="notice notice-error">{{ formError }}</div><div class="flex gap-3 border-t border-slate-100 pt-4"><button type="button" class="btn-ghost flex-1 border border-slate-200" @click="providerForm.open=false">取消</button><button class="btn-primary flex-1" :disabled="saving">{{ saving ? '保存中...' : '保存 Provider' }}</button></div></form></Modal>

    <Modal v-if="recordForm.open" @close="recordForm.open=false"><form class="space-y-5" @submit.prevent="saveRecord"><div><div class="eyebrow">MANAGED RECORD</div><h2 class="mt-1 text-lg font-bold text-slate-900">{{ recordForm.id ? '编辑托管记录' : '添加托管记录' }}</h2></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label class="field-label">DNS Provider</label><select v-model="recordForm.provider_id" class="input"><option v-for="provider in store.dnsProviders" :key="provider.id" :value="provider.id">{{ provider.name }} · {{ provider.zone }}</option></select></div><div><label class="field-label">记录来源</label><select v-model="recordForm.source" class="input"><option value="manual">手动填写记录值</option><option value="agent">选择 CDT Relay Agent</option></select></div><div><label class="field-label">记录类型</label><select v-model="recordForm.type" class="input"><option value="A">A</option><option value="AAAA">AAAA</option><option value="CNAME">CNAME</option><option value="TXT">TXT</option></select></div><div><label class="field-label">记录名</label><input v-model="recordForm.name" class="input" placeholder="relay 或 relay.example.com" /></div><div v-if="recordForm.source === 'agent'" class="sm:col-span-2"><template v-if="recordForm.id"><label class="field-label">CDT Relay Agent</label><select v-model="recordForm.relay_node_id" class="input"><option value="">请选择已安装 Agent 的节点</option><option v-for="node in store.relayNodes" :key="node.id" :value="node.id">{{ node.name }} · {{ node.public_ip || '未上报 IP' }} · {{ node.status }}</option></select><p class="field-hint">编辑时调整单条记录对应的 Relay Agent。</p></template><template v-else><label class="field-label">CDT Relay Agent（可多选）</label><div class="target-picker"><label v-for="node in store.relayNodes" :key="node.id" class="target-option"><input v-model="recordForm.relay_node_ids" type="checkbox" :value="node.id" /><span class="min-w-0 flex-1"><strong>{{ node.name }}</strong><small>{{ node.public_ip || '未上报 IP' }} · {{ node.status }}</small></span></label><div v-if="!store.relayNodes.length" class="empty-picker">暂无已注册 Relay Agent</div></div><p class="field-hint">可同时选择多台 Relay；每台 Agent 会生成一条同名 A/AAAA 记录，离线时自动停用。</p></template></div><div v-else class="sm:col-span-2"><label class="field-label">记录值</label><input v-model="recordForm.value" class="input" placeholder="例如：203.0.113.10" /></div><div><label class="field-label">TTL（秒）</label><input v-model.number="recordForm.ttl" type="number" min="30" max="86400" class="input" /></div><label class="flex items-center gap-2 self-end pb-2 text-sm text-slate-600"><input v-model="recordForm.enabled" type="checkbox" />启用托管</label></div><div v-if="formError" class="notice notice-error">{{ formError }}</div><div class="flex gap-3 border-t border-slate-100 pt-4"><button type="button" class="btn-ghost flex-1 border border-slate-200" @click="recordForm.open=false">取消</button><button class="btn-primary flex-1" :disabled="saving">{{ saving ? '保存中...' : '保存记录' }}</button></div></form></Modal>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRelayStore } from '../stores/relay'
import Modal from '../components/Modal.vue'

const store = useRelayStore(); const syncing = ref(false); const busyId = ref(''); const saving = ref(false); const formError = ref(''); const message = ref({ type: 'success', text: '' })
const providerForm = reactive({ open: false, id: '', name: '', type: 'aliyun', zone: '', zone_id: '', endpoint: '', access_key_id: '', access_key_secret: '', api_token: '', enabled: true })
const recordForm = reactive({ open: false, id: '', provider_id: '', source: 'manual', relay_node_id: '', relay_node_ids: [], name: '', type: 'A', value: '', ttl: 60, enabled: true })
const recordsFor = id => store.dnsRecords.filter(item => item.provider_id === id)
const providerName = id => store.dnsProviders.find(item => item.id === id)?.name || id
const relayNodeName = id => store.relayNodes.find(item => item.id === id)?.name || id
function credentialLabel(provider) { return provider.type === 'cloudflare' ? (provider.token_configured ? 'Token 已配置' : '未配置') : (provider.secret_configured ? 'AK 已配置' : '未配置') }
function formatTime(value) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '未测试' }
function statusLabel(value) { return { synced: '已同步', pending: '待同步', disabled: '已停用', error: '同步失败' }[value] || value }
function showMessage(text, type = 'success') { message.value = { text, type }; window.setTimeout(() => { message.value = { text: '', type: 'success' } }, 5000) }
function openProvider(provider) { formError.value = ''; Object.assign(providerForm, provider ? { open: true, id: provider.id || '', name: provider.name || '', type: provider.type || 'aliyun', zone: provider.zone || '', zone_id: provider.zone_id || '', endpoint: provider.endpoint || '', access_key_id: provider.access_key_id || '', access_key_secret: '', api_token: '', enabled: provider.enabled !== false } : { open: true, id: '', name: '', type: 'aliyun', zone: '', zone_id: '', endpoint: '', access_key_id: '', access_key_secret: '', api_token: '', enabled: true }) }
async function saveProvider() { saving.value = true; formError.value = ''; const payload = { name: providerForm.name, type: providerForm.type, zone: providerForm.zone, zone_id: providerForm.zone_id, endpoint: providerForm.endpoint, access_key_id: providerForm.access_key_id, access_key_secret: providerForm.access_key_secret, api_token: providerForm.api_token, enabled: providerForm.enabled }; try { if (providerForm.id) await store.updateDNSProvider(providerForm.id, payload); else await store.createDNSProvider(payload); providerForm.open = false; showMessage('DNS Provider 已保存') } catch (e) { formError.value = e.response?.data?.error || '保存失败' } finally { saving.value = false } }
async function testProvider(provider) { busyId.value = provider.id; try { await store.testDNSProvider(provider.id); showMessage('Provider 连接测试成功') } catch (e) { showMessage(e.response?.data?.error || 'Provider 测试失败', 'error') } finally { busyId.value = '' } }
async function syncProvider(provider) { busyId.value = provider.id; try { const data = await store.syncDNSProvider(provider.id); showMessage(`同步完成：新增 ${data.result?.created || 0}，更新 ${data.result?.updated || 0}，删除 ${data.result?.deleted || 0}`) } catch (e) { showMessage(e.response?.data?.error || 'DNS 同步失败', 'error') } finally { busyId.value = '' } }
async function syncAll() { syncing.value = true; try { const data = await store.syncAllDNS(); if (data.ok === false) throw new Error(data.error || '部分 Provider 同步失败'); showMessage('全部 DNS Provider 已同步') } catch (e) { showMessage(e.response?.data?.error || e.message || 'DNS 同步失败', 'error') } finally { syncing.value = false } }
async function removeProvider(provider) { if (!window.confirm(`确认删除 DNS Provider“${provider.name}”？请先确认它没有托管记录。`)) return; try { await store.deleteDNSProvider(provider.id); showMessage('DNS Provider 已删除') } catch (e) { showMessage(e.response?.data?.error || '删除失败', 'error') } }
function openRecord(record) { formError.value = ''; Object.assign(recordForm, record ? { open: true, id: record.id, provider_id: record.provider_id, source: record.relay_node_id ? 'agent' : 'manual', relay_node_id: record.relay_node_id || '', relay_node_ids: record.relay_node_id ? [record.relay_node_id] : [], name: record.name || '', type: record.type || 'A', value: record.value || '', ttl: record.ttl || 60, enabled: record.desired_enabled !== false } : { open: true, id: '', provider_id: store.dnsProviders[0]?.id || '', source: 'manual', relay_node_id: '', relay_node_ids: [], name: '', type: 'A', value: '', ttl: 60, enabled: true }) }
async function saveRecord() { saving.value = true; formError.value = ''; const selectedRelayNodeIDs = recordForm.id ? [recordForm.relay_node_id].filter(Boolean) : [...recordForm.relay_node_ids]; if (recordForm.source === 'agent' && !selectedRelayNodeIDs.length) { formError.value = '请至少选择一台 CDT Relay Agent'; saving.value = false; return } const payload = { provider_id: recordForm.provider_id, name: recordForm.name, type: recordForm.type, value: recordForm.source === 'agent' ? '' : recordForm.value, ttl: Number(recordForm.ttl), enabled: recordForm.enabled }; if (recordForm.source === 'agent') { if (recordForm.id) payload.relay_node_id = selectedRelayNodeIDs[0]; else payload.relay_node_ids = selectedRelayNodeIDs } try { if (recordForm.id) await store.updateDNSRecord(recordForm.id, payload); else await store.createDNSRecord(payload); recordForm.open = false; showMessage(recordForm.id || selectedRelayNodeIDs.length < 2 ? '托管记录已保存，等待同步' : `已为 ${selectedRelayNodeIDs.length} 台 Relay 创建记录，等待同步`) } catch (e) { formError.value = e.response?.data?.error || '保存失败' } finally { saving.value = false } }
async function removeRecord(record) { if (!window.confirm(`确认删除托管记录“${record.name}”？`)) return; try { await store.deleteDNSRecord(record.id); showMessage('托管记录已删除，下一次同步会清理对应 DNS 记录') } catch (e) { showMessage(e.response?.data?.error || '删除失败', 'error') } }
onMounted(async () => { await Promise.all([store.fetchDNSProviders(), store.fetchDNSRecords(), store.fetchRelayNodes()]) })
</script>

<style scoped>
.eyebrow{color:#2563eb;font-size:10px;font-weight:800;letter-spacing:.16em}.page-title{margin-top:5px;color:#172033;font-size:27px;font-weight:750;letter-spacing:-.03em}.page-subtitle{margin-top:5px;color:#64748b;font-size:12px}.provider-mark{display:inline-flex;width:30px;height:25px;align-items:center;justify-content:center;border-radius:7px;background:#eff6ff;color:#2563eb;font-size:9px;font-weight:800;letter-spacing:.04em}.state-tag{border-radius:999px;background:#f1f5f9;padding:5px 9px;color:#64748b;font-size:10px;font-weight:700}.state-online{background:#ecfdf3;color:#15803d}.state-error{background:#fef2f2;color:#b91c1c}.info-box{min-width:0;border-radius:8px;background:#f8fafc;padding:9px}.info-box span{display:block;color:#94a3b8;font-size:9px}.info-box strong{display:block;overflow:hidden;margin-top:4px;color:#475569;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.record-type{border-radius:5px;background:#f1f5f9;padding:3px 5px;color:#64748b;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px;font-weight:700}.record-row{display:flex;align-items:center;gap:16px;padding:14px 20px}.target-picker{max-height:240px;overflow:auto;border:1px solid #e5eaf1;border-radius:9px}.target-option{display:flex;align-items:center;gap:9px;padding:10px 12px;border-bottom:1px solid #f1f5f9}.target-option:last-child{border:0}.target-option strong,.target-option small{display:block}.target-option strong{color:#475569;font-size:11px}.target-option small{margin-top:2px;color:#94a3b8;font-size:9px}.empty-picker{padding:16px;color:#94a3b8;font-size:11px;text-align:center}.empty-panel{padding:48px;text-align:center;color:#94a3b8;font-size:12px}.field-hint{margin-top:5px;color:#94a3b8;font-size:10px}
@media(max-width:639px){.record-row{align-items:flex-start;flex-direction:column;gap:10px}.record-row>div:last-child{width:100%;justify-content:flex-end}}
</style>
