<template>
  <div class="space-y-5 fade-in">
    <header class="flex flex-wrap items-end justify-between gap-4"><div><div class="eyebrow">LANDING NODES</div><h1 class="page-title">落地节点</h1><p class="page-subtitle">SS2022、VLESS、REALITY 等实际服务端地址</p></div><button class="btn-primary" @click="openCreate">添加落地节点</button></header>
    <div v-if="message" class="notice" :class="messageType==='error'?'notice-error':'notice-success'">{{ message }}</div>
    <div class="card overflow-hidden"><div v-if="!store.landingNodes.length" class="empty-panel">还没有落地节点</div><div v-else class="node-table"><div class="table-head"><span>节点</span><span>地址</span><span>协议</span><span>状态</span><span></span></div><div v-for="node in store.landingNodes" :key="node.id" class="table-row"><div class="min-w-0"><strong class="block truncate text-sm text-slate-800">{{ node.name }}</strong><small class="mt-1 block truncate font-mono text-[10px] text-slate-400">{{ node.id }}</small></div><span class="truncate text-xs text-slate-600">{{ node.address }}:{{ node.port }}</span><span class="protocol-tag">{{ node.network.toUpperCase() }}</span><span class="state-tag" :class="node.enabled?'state-online':''">{{ node.enabled?'启用':'停用' }}</span><div class="flex justify-end gap-1"><button class="btn-ghost px-2 py-1 text-xs" @click="openEdit(node)">编辑</button><button class="btn-danger px-2 py-1 text-xs" @click="remove(node)">删除</button></div></div></div></div>

    <Modal v-if="showForm" @close="showForm=false"><form class="space-y-5" @submit.prevent="save"><div><div class="eyebrow">LANDING</div><h2 class="mt-1 text-lg font-bold text-slate-900">{{ editTarget?'编辑落地节点':'添加落地节点' }}</h2></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="field-label">节点名称</label><input v-model="form.name" class="input" placeholder="例如：香港 SS2022 主节点" /></div><div><label class="field-label">IP 或域名</label><input v-model="form.address" class="input" placeholder="1.2.3.4" /></div><div><label class="field-label">服务端口</label><input v-model.number="form.port" type="number" min="1" max="65535" class="input" /></div><div><label class="field-label">网络协议</label><select v-model="form.network" class="input"><option value="tcp">TCP</option><option value="udp">UDP</option><option value="tcp+udp">TCP + UDP</option></select></div><label class="flex items-center gap-2 self-end pb-2 text-sm text-slate-600"><input v-model="form.enabled" type="checkbox" />启用节点</label></div><div v-if="formError" class="notice notice-error">{{ formError }}</div><div class="flex gap-3 border-t border-slate-100 pt-4"><button type="button" class="btn-ghost flex-1 border border-slate-200" @click="showForm=false">取消</button><button class="btn-primary flex-1" :disabled="saving">{{ saving?'保存中...':'保存' }}</button></div></form></Modal>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useRelayStore } from '../stores/relay'
import Modal from '../components/Modal.vue'
const store=useRelayStore();const showForm=ref(false);const editTarget=ref(null);const saving=ref(false);const formError=ref('');const message=ref('');const messageType=ref('success')
const empty=()=>({name:'',address:'',port:443,network:'tcp',enabled:true});const form=ref(empty())
function openCreate(){editTarget.value=null;form.value=empty();formError.value='';showForm.value=true}function openEdit(node){editTarget.value=node;form.value={name:node.name,address:node.address,port:node.port,network:node.network,enabled:node.enabled};formError.value='';showForm.value=true}
async function save(){saving.value=true;formError.value='';try{if(editTarget.value)await store.updateLandingNode(editTarget.value.id,form.value);else await store.createLandingNode(form.value);showForm.value=false;showMessage('保存成功')}catch(e){formError.value=e.response?.data?.error||'保存失败'}finally{saving.value=false}}
async function remove(node){if(!confirm(`确认删除落地节点“${node.name}”？`))return;try{await store.deleteLandingNode(node.id);showMessage('删除成功')}catch(e){showMessage(e.response?.data?.error||'节点正在被转发服务使用，无法删除','error')}}
function showMessage(text,type='success'){message.value=text;messageType.value=type;setTimeout(()=>message.value='',4000)}onMounted(()=>store.fetchLandingNodes())
</script>

<style scoped>
.eyebrow{color:#2563eb;font-size:10px;font-weight:800;letter-spacing:.16em}.page-title{margin-top:5px;color:#172033;font-size:27px;font-weight:750;letter-spacing:-.03em}.page-subtitle{margin-top:5px;color:#64748b;font-size:12px}.table-head,.table-row{display:grid;grid-template-columns:minmax(150px,1.2fr) minmax(160px,1fr) 90px 70px 110px;align-items:center;gap:12px;padding:12px 18px}.table-head{border-bottom:1px solid #eef2f7;background:#f8fafc;color:#94a3b8;font-size:9px;font-weight:700;letter-spacing:.08em}.table-row{border-bottom:1px solid #f1f5f9}.protocol-tag,.state-tag{width:max-content;border-radius:999px;background:#f1f5f9;padding:4px 8px;color:#64748b;font-size:9px;font-weight:700}.state-online{background:#ecfdf3;color:#15803d}.empty-panel{padding:52px;text-align:center;color:#94a3b8;font-size:12px}@media(max-width:720px){.table-head{display:none}.table-row{grid-template-columns:minmax(0,1fr) auto;padding:14px}.table-row>span:nth-of-type(1){grid-column:1/2}.table-row>span:nth-of-type(2),.table-row>span:nth-of-type(3){display:none}.table-row>div:last-child{grid-column:1/-1;justify-content:flex-start;border-top:1px solid #f1f5f9;padding-top:8px}.node-table{display:grid;gap:10px;padding:10px}.table-row{border:1px solid #e5eaf1;border-radius:10px}}
</style>
